---
name: "Check Changelog"
description: "Verify many things in changelog"

inputs:
  python-version:
    description: "Python version to use with uv"
    required: false
    default: "3.12"
  working-directory:
    description: "Directory where the command will be executed"
    required: false
    default: "."
  format-check:
    description: "Whether to run the check-format step (boolean)"
    required: false
    default: "false"
  tag-check:
    description: "Tag to verify"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "${{ inputs.python-version }}"
    - id: format
      name: Check format
      if: ${{ fromJSON(inputs.format-check) }}
      shell: bash
      run: |
        uv run --with '${{ github.action_path }}' \
          changelogtxt check-format \
          -f ${{ inputs.working-directory }}
    - id: tag
      name: Check tag
      if: ${{ inputs.tag-check != '' }}
      shell: bash
      run: |
        uv run --with '${{ github.action_path }}' \
          changelogtxt check-tag \
          -f ${{ inputs.working-directory }}
          -t "${{ inputs.tag-check }}" \
