---
name: "Check Changelog"
description: "Verify many things in changelog"

inputs:
  python-version:
    description: "Python version to use with uv"
    required: false
    default: "3.12"
  working-directory:
    description: "Directory where the command will be executed"
    required: false
    default: "."
  format-check:
    description: "Whether to run the check-format step (boolean)"
    required: false
    default: "true"
  tag-check:
    description: "If a version number supplied, ensure changelogtxt-parser contains it."
    required: false
    default: ""
  summarize-news:
    description: "Supply an origin and destination (branch? file? what?) to print the novelties."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "${{ inputs.python-version }}"
    - id: format
      name: Check format
      if: ${{ fromJSON(inputs.format-check) }}
      shell: bash
      run: |
        set -euo pipefail
        echo "Checking format..."
        uv run --with '${{ github.action_path }}' \
          changelogtxt check-format \
          -f ${{ inputs.working-directory }}
    - id: tag
      name: Check tag
      if: ${{ inputs.tag-check != '' }}
      shell: bash
      run: |
        set -euo pipefail
        echo "Checking tag..."
        uv run --with '${{ github.action_path }}' \
          changelogtxt check-tag ${{ inputs.tag-check }} \
          -f ${{ inputs.working-directory }}
    - id: summarize
      name: Summarize News
      if: ${{ inputs.summarize-news != '' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        set -euo pipefail
        echo "Summarizing news..."
        read origin target <<< "${{ inputs.summarize-news }}"
        echo "Origin: $origin"
        echo "Target: $target"
        uv run --with '${{ github.action_path }}' \
          changelogtxt summarize-news "$origin" "$target"
